vim.g.mapleader = " "
vim.keymap.set("n", "<leader>x", "<cmd> :bdelete <cr>")
vim.keymap.set("n", "<leader>", vim.cmd.NvimTreeToggle)
vim.keymap.set("n", "<C-d>", "<C-d>zz")
vim.keymap.set("v", "J", ":m '>+1<CR>gv=gv")
vim.keymap.set("v", "K", ":m '<-2<CR>gv=gv")
vim.keymap.set("n", "<C-u>", "<C-u>zz")
vim.keymap.set("n", "<C-v>", '"+p"')
vim.keymap.set("n", "<C-c>", '"+y"')
vim.keymap.set("n", "<C-l>", vim.cmd.Lazy)
vim.keymap.set("n", "M", vim.cmd.Mason)
vim.keymap.set("n", "git", vim.cmd.LazyGit)
vim.keymap.set("n", "W", "<cmd> w<CR>")
vim.keymap.set("n", "wq", "<cmd> wq<CR>")
vim.keymap.set("n", "Q", "<cmd> q<CR>")
vim.keymap.set("n", "qq", "<cmd> qa<CR>")
vim.keymap.set("n", "so", "<cmd> so<CR>")
vim.keymap.set("n", "<leader>xx", function()
	require("trouble").toggle()
end)
vim.keymap.set("n", "<leader>n", "<cmd> bn <cr>")
vim.keymap.set("n", "<leader>xw", function()
	require("trouble").toggle("workspace_diagnostics")
end)
vim.keymap.set("n", "<leader>xd", function()
	require("trouble").toggle("document_diagnostics")
end)
vim.keymap.set("n", "qf", function()
	require("trouble").toggle("quickfix")
end)
vim.keymap.set("n", "<leader>xl", function()
	require("trouble").toggle("loclist")
end)
vim.keymap.set("n", "gR", function()
	require("trouble").toggle("lsp_references")
end)
vim.keymap.set("n", "vs", "<cmd> :vs <cr>")
vim.keymap.set("n", "nd", ":NoiceDismiss<CR>", { silent = true })
vim.keymap.set("n", "ee", "$")
vim.keymap.set("v", "ee", "$")
vim.keymap.set("v", "K", ":move '<-2<CR>gv=gv", { silent = true })
vim.keymap.set("v", "J", ":move '>+1<CR>gv=gv", { silent = true })
